# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: cinit

env:
 - GO111MODULE=on
 - GOPROXY=https://proxy.golang.org

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
      - PACKAGE=github.com/techniumlabs/cinit
    ldflags:
      - -w -s -X {{.Env.PACKAGE}}/cmd.version={{.Version}} -X {{.Env.PACKAGE}}/cmd.commit={{ .ShortCommit }} -X {{.Env.PACKAGE}}/cmd.date={{.Date}}
archives:
- replacements:
    darwin: darwin
    linux: linux
    windows: windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
